{ config, lib, pkgs, modulesPath, ... }:

# PLACEHOLDER - DO NOT USE AS-IS.
#
# This file is always machine-generated by `nixos-generate-config` when you
# boot the NixOS installer on the target disk. Real disk UUIDs, the exact
# kernel modules needed for initrd, and the correct swap/fs entries can only
# be known once you're actually partitioning that machine - hand-writing
# them here would risk an unbootable system, so this is deliberately left
# as a documented stub rather than guessed values.
#
# What to do at install time:
#   1. Boot the NixOS ISO, partition the disk (matching the current layout
#      is fine: FAT32 ESP for /boot, Btrfs for /, or start fresh).
#   2. Run `nixos-generate-config --root /mnt`.
#   3. Copy the generated /mnt/etc/nixos/hardware-configuration.nix over
#      this file, replacing it entirely.
#
# For reference, the current Arch layout on this machine (bumblebee) being
# replaced is:
#   - nvme0n1p1: vfat (FAT32), mounted /boot  (EFI system partition)
#   - nvme0n1p2: btrfs, mounted /, options: compress=zstd:3,ssd,discard=async,space_cache=v2
#   - zram0: swap
#   - CPU: AMD Ryzen AI 7 350 w/ Radeon 860M (x86_64)

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" ];
  boot.kernelModules = [ "amdgpu" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/REPLACE_ME";
    fsType = "btrfs";
    options = [ "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/REPLACE_ME";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
